In [8]:
import numpy as np

# NumPy is the fundamental package for scientific computing with Python.
# It has a powerful N-dimensional array object (numpy.ndarray):
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a.shape

(3, 5)

In [10]:
a.ndim

2

In [11]:
a.dtype

dtype('int32')

In [15]:
a.size

15

In [16]:
type(a)

numpy.ndarray

In [18]:
np.ones((2, 3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [19]:
np.arange(0, 2, 0.25) # floating point precision is finite

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

In [20]:
np.linspace(0, 2, 9) # better

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
# Financial: mortgage payment
np.pmt(.04 / 12, 360, 1000000)

-4774.152954654538

In [22]:
# Linear Algebra: solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8
e1 = np.array([[3, 1], [1, 2]])
e2 = np.array([9, 8])
np.linalg.solve(e1, e2)

array([2., 3.])

In [26]:
# Matrix multiplication
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
print(A*B)      # elementwise product
print(A.dot(B)) # matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


More: https://docs.scipy.org/doc/numpy/user/quickstart.html